# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

box = "rhel7-server-x64-base"
url = ""
hostname = ""
domain = ""
ip = ""
ram = "4096"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = box
  
  #config.vm.box_url = url
  #config.vm.host_name = hostname + "." + domain
  #config.vm.network "private_network", ip: ip, auto_config: false

  config.vm.provision "shell", path: "../common/java.sh"
  
  # Jenkins
  config.vm.provision "shell", path: "../common/jenkins.sh"
  config.vm.network :forwarded_port, host: 8080, guest: 8080
  
  # Thoughtworks Go
  config.vm.provision "shell", path: "../commonn/go-cd.sh"
  config.vm.network :forwarded_port, host: 8153, guest: 8153
  
  # Docker Registry
  config.vm.provision "shell", path: "docker-registry.sh"
  config.vm.network :forwarded_port, host: 5000, guest: 5000

  # VirtualBox customization
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", ram]
  end

  # Synced folders
  # See https://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  config.vm.synced_folder "containers", "/opt/docker-image"
  config.vm.synced_folder "../common", "/opt/common"

  # Provision Docker containers
  config.vm.provision "shell", path: "build_and_deploy_stash_jira.sh"

  # JIRA
  config.vm.network :forwarded_port, host: 9080, guest: 9080

  # Stash
  config.vm.network :forwarded_port, host: 7990, guest: 7990
  
end
