#!/bin/bash

trap 'exit' ERR

# Set local variables
VAGRANT_HOME=/home/vagrant
GIT_VERSION=2.0.1


# Source and Register this RHEL instance with Red Hat Customer Portal
# $rcp_user and $rcp_password are externalized in rhcp.properties which is generated by rhcp.sh
# These are your Red Hat Customer Portal credentials
. $VAGRANT_HOME/rhcp.properties
subscription-manager register --username $username --password $password --auto-attach

yum update -y
yum install -y bzip2 curl gcc "kernel-devel-$(uname -r)" kernel-headers wget
yum install -y net-tools
yum groupinstall -y "Development Tools" "X Window System"

# disable unnecessary services
systemctl disable acpid.service
systemctl disable auditd.service
systemctl disable blk-availability.service
systemctl disable bluetooth.service
systemctl disable certmonger.service
systemctl disable cpuspeed.service
systemctl disable cups.service
systemctl disable haldaemon.service
systemctl disable ip6tables.service
systemctl disable lvm2-monitor.service
systemctl disable messagebus.service
systemctl disable mdmonitor.service
systemctl disable rpcbind.service
systemctl disable rpcgssd.service
systemctl disable rpcidmapd.service
systemctl disable yum-updateonboot.service

# sudo
yum install -y sudo
echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/vagrant

# Get and install EPEL
wget http://mirrors.mit.edu/epel/beta/7/x86_64/epel-release-7-0.2.noarch.rpm
chown vagrant:vagrant $VAGRANT_HOME/epel-release-7-0.2.noarch.rpm
yum -y install epel-release-7-0.2.noarch.rpm


# Install Git
yum -y install curl-devel expat-devel gettext-devel perl-ExtUtils-MakeMaker
wget https://www.kernel.org/pub/software/scm/git/git-$GIT_VERSION.tar.gz
chown vagrant:vagrant $VAGRANT_HOME/git-$GIT_VERSION.tar.gz
tar xzf git-$GIT_VERSION.tar.gz
cd git-$GIT_VERSION
make prefix=/usr/local/git all
make prefix=/usr/local/git install
echo "export PATH=/usr/local/git/bin:$PATH" >> /etc/bashrc
source /etc/bashrc


# Install debootstrap (for building Docker base containers)
yum install -y debootstrap


# Install docker
yum install -y docker-io
systemctl enable docker.service
echo -e 'DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"\n' > /etc/default/docker
systemctl start docker.service
systemctl status docker.service
usermod -a -G docker vagrant

# Import Red Hat 7 container
# @see https://docs.docker.com/reference/commandline/cli/#import
cat $VAGRANT_HOME/rhel-server-docker-7.0-21.4-x86_64.tar.gz | docker import - rhel:rhel7


# Make other repositories available
subscription-manager repos --enable rhel-7-server-optional-rpms 
subscription-manager repos --enable rhel-7-server-extras-rpms
subscription-manager repos --enable rhel-7-server-thirdparty-oracle-java-rpms

yum clean all
