#!/bin/bash

trap 'exit' ERR

# Set local variables
VAGRANT_HOME=/home/vagrant
GIT_VERSION=2.0.4

# Source and Register this RHEL instance with Red Hat Customer Portal
# $rcp_user and $rcp_password are externalized in rhcp.properties which is generated by rhcp.sh
# These are your Red Hat Customer Portal credentials
. $VAGRANT_HOME/rhcp.properties
subscription-manager register --username $username --password $password --auto-attach

# Make other repositories available
subscription-manager repos --enable rhel-7-server-optional-rpms 
subscription-manager repos --enable rhel-7-server-extras-rpms
subscription-manager repos --enable rhel-7-server-thirdparty-oracle-java-rpms


# sudo
yum install -y bzip2 curl gcc "kernel-devel-$(uname -r)" kernel-devel kernel-headers wget net-tools sudo
yum groupinstall -y "Development Tools" "X Window System"


# Get and install Git
yum -y install curl-devel expat-devel gettext-devel openssl openssl-devel zlib-devel perl-ExtUtils-MakeMaker
wget --retry-connrefused https://www.kernel.org/pub/software/scm/git/git-$GIT_VERSION.tar.gz
chown vagrant:vagrant $VAGRANT_HOME/git-$GIT_VERSION.tar.gz
tar xzf git-$GIT_VERSION.tar.gz
cd git-$GIT_VERSION
make prefix=/usr/local/git all
make prefix=/usr/local/git install
echo "export PATH=/usr/local/git/bin:$PATH" >> /etc/bashrc
source /etc/bashrc
rm -rf $VAGRANT_HOME/git-$GIT_VERSION*

# Install Docker and start service
yum install -y docker
systemctl enable docker.service
echo -e 'DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"\n' > /etc/sysconfig/docker
systemctl start docker.service
systemctl status docker.service
usermod -a -G docker vagrant

# Import Red Hat 7 container
# @see https://docs.docker.com/reference/commandline/cli/#import
cat $VAGRANT_HOME/rhel-server-docker-7.0-21.4-x86_64.tar.gz | docker import - rhel:rhel7

# Provide means for entering a running Docker container other than SSH
# @see https://github.com/Pithikos/docker-enter
# wget https://raw.githubusercontent.com/Pithikos/docker-enter/master/docker-enter.c
# chown vagrant:vagrant $VAGRANT_HOME/docker-enter.c
# chmod +w $VAGRANT_HOME/docker-enter.c
# gcc $VAGRANT_HOME/docker-enter.c -o docker-enter
# rm -f $VAGRANT_HOME/docker-enter.c

# Install appliance-tools. 
# Appliance tools is one method that can be used for creating a VM that can be packaged into a docker container.
yum install -y appliance-tools libguestfs-tools

# Clean up
yum clean all

# Configure Other System Services
systemctl disable acpid.service 
# systemctl disable auditd.service 
# systemctl disable blk-availability.service 
systemctl disable bluetooth.service 
systemctl disable certmonger.service 
systemctl disable cpuspeed.service 
systemctl disable cups.service 
# systemctl disable haldaemon.service 
# systemctl disable ip6tables.service 
systemctl disable lvm2-monitor.service 
systemctl disable messagebus.service 
systemctl disable mdmonitor.service 
# systemctl disable rpcbind.service 
# systemctl disable rpcgssd.service 
# systemctl disable rpcidmapd.service 
systemctl disable yum-updateonboot.service 
