task :default => [
  "target/trusty64.tar.gz", :ci,
  :base, :x,
  :gcc, :python27, :nodejs, :openjdk7, :scala210, :ruby2, :jruby, :r, :octave,
  :nginx, :graphite, :statsd, :jenkins, :zookeeper, :mesos, :marathon, :chronos,
  :ipython, :lighttable, :scraping, :phantomjs, :slimerjs,
  :gnuplot, :graphviz, :tabula, :tesseract, :vowpalwabbit
]

def build(container)
   sh "docker build --rm=true -t laika/#{container} containers/#{container}"
end


################################################################################
# Spaceport containers
################################################################################

file "target/trusty64.tar.gz" do
  sh "mkdir -p target"
  sh "sudo rm -fr /tmp/trusty64 && mkdir -p /tmp/trusty64"

  # Must be root to debootstrap and can't on Virtualbox shared directory filesystem.
  sh "sudo debootstrap --variant=minbase trusty /tmp/trusty64"
  sh "sudo tar -C /tmp/trusty64 -c . -zf target/trusty64.tar.gz"
  sh "sudo rm -fr /tmp/trusty64"

  sh "sudo chown vagrant target/trusty64.tar.gz"
  sh "cat target/trusty64.tar.gz | docker import - laika/trusty64"
end

task :ci => :jenkins do
  sh "docker build --rm=true -t laika/ci ci"
end


################################################################################
# Base containers
################################################################################

task :base => "target/trusty64.tar.gz" do
  build("base")
end

task :x => :base do
  build("x")
end


################################################################################
# Compiler/interpreter containers
################################################################################

task :gcc => :base do
  build("gcc")
end

task :python27 => :gcc do
  build("python27")
end

task :nodejs => :base do
  build("nodejs")
end

task :openjdk7 => :base do
  build("openjdk7")
end

task :scala210 => :openjdk7 do
  build("scala210")
end

task :ruby2 => :base do
  build("ruby2")
end

task :jruby => :openjdk7 do
  build("jruby")
end

task :r => :gcc do
  build("r")
end

task :octave => :base do
  build("octave")
end


################################################################################
# Service containers
################################################################################

task :nginx => :base do
  build("nginx")
end

task :graphite => :python27 do
  build("graphite")
end

task :statsd => :graphite do
  build("statsd")
end

task :jenkins => :openjdk7 do
  build("jenkins")
end

task :zookeeper => :openjdk7 do
  build("zookeeper")
end

task :mesos => :zookeeper do
  build("mesos")
end

task :marathon => :mesos do
  build("marathon")
end

task :chronos => :mesos do
  build("chronos")
end


################################################################################
# Development containers
################################################################################

task :ipython => :python27 do
  build("ipython")
end

task :lighttable => :python27 do
  build("lighttable")
end

task :scraping => :python27 do
  build("scraping")
end

task :phantomjs => :nodejs do
  build("phantomjs")
end

task :slimerjs => :nodejs do
  build("slimerjs")
end


################################################################################
# Application containers
################################################################################

task :gnuplot => :base do
  build("gnuplot")
end

task :graphviz => :base do
  build("graphviz")
end

task :tabula => :jruby do
  build("tabula")
end

task :tesseract => :base do
  build("tesseract")
end

task :vowpalwabbit => :base do
  build("vowpalwabbit")
end
