$install_script = <<SCRIPT

  # Provisioning script must be idempotent.

  trap 'exit' ERR

  ##############################################################################
  # Update VM
  ##############################################################################

  yum update -y
  yum upgrade -y

  ##############################################################################
  # Install Docker Registry
  # for hosting Docker containers
  ##############################################################################

  yum -y install docker-registry
  systemctl enable docker-registry.service
  systemctl start docker-registry.service
  systemctl status docker-registry.service

  DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --net=host"
  systemctl restart docker.service

SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "centos-7.0-x64"
  #config.vm.hostname = "factory"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provision "shell" do |s|
    s.inline = $install_script
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
  end
  
  # Synced folders
  # See https://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  config.vm.synced_folder "containers", "/opt/containers"

  # Docker
  # @see https://docs.vagrantup.com/v2/provisioning/docker.html
  config.vm.provision "docker" do |d|

    d.build_image "/opt/containers/base", args: "--rm=true -t fans/factory-base"
    d.build_image "/opt/containers/oraclejdk7", args: "--rm=true -t fans/oraclejdk7"
    d.build_image "/opt/containers/postgresql94", args: "--rm=true -t fans/postgresql94"
    d.build_image "/opt/containers/atlassian", args: "--rm=true -t fans/atlassian"
    d.build_image "/opt/containers/nginx", args: "--rm=true -t fans/nginx"
    d.build_image "/opt/containers/jenkins", args: "--rm=true -t fans/jenkins"
    d.build_image "/opt/containers/go-server", args: "--rm=true -t fans/go-server"
    d.build_image "/opt/containers/go-agent", args: "--rm=true -t fans/go-agent"
    d.build_image "/opt/containers/stash", args: "--rm=true -t fans/stash"
    d.build_image "/opt/containers/jira", args: "--rm=true -t fans/jira"

    d.run "fans/factory-base", args: "-p 2000:22"
    d.run "fans/oraclejdk7"
    d.run "fans/postgresql94", auto_assign_name: false, args: "--name db -p 5432:5432"
    d.run "fans/atlassian", cmd: "/usr/local/share/atlassian/initialise_db.sh"
    d.run "fans/nginx", args: "-p 8000:80"
    d.run "fans/jenkins", args: "-p 8080:8080"
    d.run "fans/go-server", args: "-p 8153:8153"
    d.run "fans/go-agent", args: "-e SERVER_PORT_8153_TCP_ADDR=localhost -e SERVER_PORT_8153_TCP_PORT=8153"
    d.run "fans/stash", auto_assign_name: false, args: "--name stash -p 7990:7990 --link db:db"
    d.run "fans/jira", args: "-p 9080:9080 --link db:db --link stash:stash"

  end

  # Ports
  config.vm.network :forwarded_port, guest: 2000, host: 2000   # factory (base)
  config.vm.network :forwarded_port, guest: 4243, host: 4243   # docker
  config.vm.network :forwarded_port, host: 5000, guest: 5000   # docker-registry
  config.vm.network :forwarded_port, guest: 5432, host: 5432   # postgresql
  config.vm.network :forwarded_port, guest: 7990, host: 7990   # stash
  config.vm.network :forwarded_port, guest: 8000, host: 80     # nginx
  config.vm.network :forwarded_port, guest: 8080, host: 8080   # jenkins
  config.vm.network :forwarded_port, guest: 8153, host: 8153   # go-server
  config.vm.network :forwarded_port, guest: 9080, host: 9080   # jira
end
